InMemeoryTest/Controllers/RentController.cs
using System;
using System.Linq;
using InMemeoryTest.Data;
using InMemeoryTest.Models;
using Microsoft.AspNetCore.Mvc;

namespace InMemeoryTest.Controllers
{
    public class RentController : Controller
    {
        private DatabaseContext _context;

        public RentController(DatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Inventories);
        }
        
        [HttpPost]
        public IActionResult Booking(int id, int count, string isReserved)
        {
            var reserved = isReserved == null ? false : true;
            var userId = _context.Clients.First(c => c.Email == User.Identity.Name).Id;
            _context.Contracts.Add(new Contract
                {ClientId = userId, Count = count, InventoryId = id, RentBeginning = DateTime.Today, IsReserved = reserved});
            _context.SaveChanges();
            return View("Index");
        }

        

        public IActionResult UserRent()
        {
            var userId = _context.Clients.First(c => c.Email == User.Identity.Name).Id;
            return View(_context.Contracts.Where(c => c.ClientId == userId));
        }

        public IActionResult FinishRent(int id)
        {
            var contract = _context.Contracts.First(c => c.Id == id);
            contract.RentEnding = DateTime.Now;
            var cost = 0;
            var dur = (contract.RentEnding - contract.RentBeginning);
            if (contract.InventoryType == InventoryType.HydroScooter)
            {
                if (dur.Minutes <= 60)
                    cost = dur.Minutes / 30 * 500;
                else
                {
                    cost = 500 * 2 + (dur.Minutes - 60) / 60 * 750;
                }
            }
            else
            {
                if (dur.Hours <= 2)
                    cost = dur.Hours * 200;
                else if(dur.Hours < 12)
                {
                    cost = 400 + (dur.Hours - 2) * 100;
                }
                else if(dur.Hours == 12)
                {
                    cost = 600;
                }
                else
                {
                    cost = 1000;
                }
            }

            contract.Cost = cost * contract.Count;
            return RedirectToAction("UserRent");
        }
    }
}

InMemeoryTest/Views/Rent/Index.cshtml
@model IEnumerable<InMemeoryTest.Models.Inventory> 
@{ 
    ViewData["Title"] = "Список"; 
} 

@foreach (var i in Model) 
   { 
        <div class="col-sm-4 col-lg-4 col-md-4"> 

            <div class="thumbnail"> 
                <div class="caption"> 
                    <h3> <a>@i.Type</a> </h3> 
                    <h3> <a>@i.Count</a> </h3> 
                    <h3> <a>@i.MinTime</a> </h3> 
                    <p class="btn btn-group pull-left">
                    @using (Html.BeginForm("Booking", "Rent", FormMethod.Post, new {enctype = "multipart/form-data"}))
                    {
                        <input type="hidden" class="form-control" name="id" value="@i.Id">
                        <input type="number" class="form-control" name="count" aria-label="Count">
                        <div class="buttons-block">
                            <div class="radio-container">
                                <div class="form-item radio-btn nth-2">
                                    <input name="isReserved" type="radio" value="true"/>
                                    <span>Забронировать</span>
                                </div>
                                <div class="form-item radio-btn nth-2">
                                    <input name="isReserved" type="radio"/>
                                    <span>Забронировать</span>
                                </div>
                            </div>
                        </div>
                        <input type="submit" class="btn btn-primary" value="Отправить"/>
                    }
                    </p> 
                </div> 
            </div> 
        </div> 
    } 

InMemeoryTest/Views/Rent/UserRent.cshtml
@model IEnumerable<InMemeoryTest.Models.Contract>

@foreach (var contract in Model)
{
    <h2>@contract.InventoryType</h2>
    <h2>@contract.Count</h2>
    <a href="~/Rent/FinishRent/@contract.Id">Завершить бронь</a>
}